[package]
name = "funften_org"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.75", features = ["backtrace"] }
glob = "0.3.1"
orgize = "0.9.0"
wire = { path = "../wire" }
