[package]
name = "core_logic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nutype = "0.3.1"
serde_json = "1.0.107"
time = "0.3.29"
