[package]
name = "yrs-kvstore-async"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.74"
smallvec = "1.11.2"
yrs = "0.17.1"
